# Time series with R

## Lesson 1: Introduction to R


```{r}
4+1

mean(c(1,2,3,4))

# These are equivalent
y=4
y<-4 #this was the original one used and that's why you will see it in many places

#load fpp2
library(fpp2)
?fpp2 

gghistogram(rnorm(200)) #rnorm generates random numbers from a standard normal

# Equivalent to typing in the help menu 
?mean 

# Example in the help menu for the mean
x <- c(0:10, 50) 
length(x)
xm <- mean(x) 


austa # what happens here? 
# Ignore the error message and keep going



# Lets look at some data sets from fpp
austa  #International vistors to Australia
autoplot(austa)


# Summary command: prints an appropriate summary of what you asked from
summary(austa)

# Some monthly data
a10 # Monthly anti-diabetic drug sales in Australia from 1992 to 2008
autoplot(a10)
summary(a10)

# You will practice reading in your own data in the tutorials this week
# and next week. This will set you up well for the assignment

# This creates a vector y of observations
y=c(1,2,3,4,5,6)
mean(y)

# Write your own function 

average<-function(x)
{
  return(sum(x)/length(x))
}

ybar<-average(y)

```


## Lesson 2: Time series graphic

```{r}
library(fpp2)

# ts objects
  
x <- c(123,39,78,52,110) # This is now just a column of numbers
x
plot(x)

  y <- ts(c(123,39,78,52,110), start=2012)
  y
plot(y)
  z <- ts(x, frequency=12, start=c(2003,1))
  z

  # For higher frequency data use the frequency argument 
  #  setwd("C:/George/Teaching/ETF3231/2018/RinLectures")
x <- scan(here::here("data","gdp.dat"))
  
ausgdp <- ts(x,frequency=4,
             start=1971.5) # Data starts in Q3
  plot(ausgdp) # part of base graphics
  autoplot(ausgdp)  # part of forecast and interaction with ggplot2
                    # better plots only for ts objects

z=rnorm(120)
#autoplot(z) 
plot(z)
  
  y <- ts(z, start=2003, frequency=12)
  attributes(y)
  autoplot(y)
  
  # Some ready ts
  elecsales
  
  ?elecsales
  # Everyone to plot
  # Also ask them to use the help command - you will need to do 
  # this a lot
  
  # ? is shorthand for help()
  
  # Ask everyone to type melsyd to see what they get
  
  melsyd # let's have a look
  head(melsyd)
  tail(melsyd)
  
  autoplot(melsyd)
  autoplot(melsyd,facets = TRUE)
  
# Back to slides
  
  # Time plot
  autoplot(melsyd[,"Economy.Class"])

  # Adding main title and 
  # also add labels to the x and y axes

  autoplot(a10) + ylab("$ million") + xlab("Year") +
    ggtitle("Antidiabetic drug sales")

  ?autoplot

# Your turn
  
  ?dole
  autoplot(dole)
  
  ?lynx
  autoplot(lynx)

  ?goog
  
  autoplot(goog)+ 
    xlab("Year") + ylab("Price ($)") + 
    ggtitle("Google closing stock price")

# Back to slides

  # The elecdaily data
  ?elecdaily
  head(elecdaily,15)
  autoplot(elecdaily)
  autoplot(elecdaily[,3])
  time(elecdaily)
  

# Seasonal plots 

  autoplot(a10)
  
  ggseasonplot(a10)
  
  
  ggseasonplot(a10, year.labels=TRUE, year.labels.left=TRUE) +
    ylab("$ million") +
    ggtitle("Seasonal plot: antidiabetic drug sales")
  
  ggseasonplot(a10, polar=TRUE) + ylab("$ million")  
  
# Seasonal subseries plots
  ggsubseriesplot(a10) + ylab("$ million") +
    ggtitle("Subseries plot: antidiabetic drug sales")
  

# Australian quarterly beer production 1956:Q1 to 2008:Q3.
  autoplot(ausbeer)
  # Take a window of it starting in 1992
  beer=window(ausbeer,start=1992)
  
  autoplot(beer)+geom_point()
    
  ggseasonplot(beer, year.labels=TRUE, 
             year.labels.left=TRUE)
  
  ggsubseriesplot(beer)+ggtitle("Subseries Plot")
  
# Students to run arrivals code below 
  # Your turn 1
  ?arrivals
  head(arrivals)
  autoplot(arrivals)  
  autoplot(arrivals, facets = TRUE)  
  
  ggseasonplot(arrivals[,"NZ"])
  ggseasonplot(arrivals[,"UK"])
  
  # Plot these together to have a closer look
  p1 <- ggseasonplot(arrivals[,"NZ"])
  p2 <- ggseasonplot(arrivals[,"UK"])
  gridExtra::grid.arrange(p1,p2,nrow=1)
  
#Back to lecture slides

  # Time series patterns
  autoplot(window(elec, start=1980)) +
    ggtitle("Australian electricity production") +
    xlab("Year") + ylab("GWh")
  
  autoplot(bricksq) +
    ggtitle("Australian clay brick production") +
    xlab("Year") + ylab("million units")
  
  autoplot(hsales) +
    ggtitle("Sales of new one-family houses, USA") +
    xlab("Year") + ylab("Total sales")
  
  autoplot(ustreas) +
    ggtitle("US Treasury Bill Contracts") +
    xlab("Day") + ylab("price")
  
  autoplot(lynx) +
    ggtitle("Annual Canadian Lynx Trappings") +
    xlab("Year") + ylab("Number trapped")
  
  
#Back to lecture slides
  
# Scatterplots
  head(motel)
    autoplot(motel[,2:1]/1000, facet=TRUE) +
    xlab("Year") + ylab("") +
    ggtitle("Total monthly accommodation: Victoria, Australia")
    
    # See what happens without the facet=TRUE argument
    autoplot(motel[,2:1]/1000)
    # doesn't make much sense because of the differences in scale
    
  qplot(Roomnights/1000, Takings/1000, data=as.data.frame(motel)) +
    ylab("Takings ($million)") + xlab("Room nights (thousands)")

  head(motel)
  head(as.data.frame(motel))

#Back to slides
  
# Lag plots and autocorrelation 
  beer <- window(ausbeer, start=1992)
  gglagplot(beer, lags=9)

  # What does the 'do.lines=FALSE' do?
  gglagplot(beer, lags=9, do.lines=FALSE)
  
# ACF
  ggAcf(beer) #from forecast package
  
  r<-ggAcf(beer)
  attributes(r)  
  r$data
  r$data$Freq
  r$data$Freq[4]
  
# Back to slides

  autoplot(goog)
  ggAcf(goog, lag.max=100)

  elec2 <- window(elec, start=1980)
  autoplot(elec2)
  
  ggAcf(elec2, lag.max=48)
  
# Students to run 
  ?usdeaths
  autoplot(usdeaths)
  ggseasonplot(usdeaths)
  gglagplot(usdeaths)
  ggAcf(usdeaths)
  
  ?sunspotarea
  autoplot(sunspotarea)
  gglagplot(sunspotarea, do.lines=FALSE)  
  ggAcf(sunspotarea)

# bAck to slides.

# White noise
  
  # Set the seed for the random number generator in R
  # This guarantees the same random numbers every time
  
  set.seed(0) 
  wn <- ts(rnorm(36)) #rnorm(n, mean = 0, sd = 1)
  autoplot(wn)+ggtitle("White noise")
  ggAcf(wn)
  
  set.seed(34) 
  wn <- ts(rnorm(36)) #rnorm(n, mean = 0, sd = 1)
  autoplot(wn)+ggtitle("White noise")
  ggAcf(wn)

  set.seed(0) 
  wn1=ts(rnorm(3600,mean=100,sd=100))
  autoplot(wn1)
  ggAcf(wn1) #lag.max
  
  set.seed(34) 
  wn1=ts(rnorm(3600,mean=100,sd=100))
  autoplot(wn1)
  ggAcf(wn1)
  
# Back to slides
# Pigs
  pigs2 <- window(pigs, start=1990)
  autoplot(pigs2) +
    xlab("Year") + ylab("thousands") +
    ggtitle("Number of pigs slaughtered in Victoria")

  ggAcf(pigs2)

# Your turn 2
  autoplot(hsales)
  ggseasonplot(hsales)
  ggsubseriesplot(hsales)
  gglagplot(hsales,do.lines=FALSE)
  ggAcf(hsales)
  
  # + Seasonality evident in all plots
  # + Cyclicity seen in first two plots
  # + No trend
  # + ACF only shows seasonality. Cycle length too long to show up here.
   
```