--- 
title: "MA 5124 Financial Time Series Analysis & Forecasting"
author: "Dr. Priyanga D. Talagala"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: rstudio/bookdown-demo
description: ""
---

# Course Syllabus {-}

\pagenumbering{arabic}

**Module Code:** MA 5124

**Title:**  Financial Time Series Analysis & Forecasting

**Credits:** 4

## Pre-requiites {-}

 None
 
## Learning Objectives {-}

- The purpose of this course is to provide students with introductory tools for the time series analysis of financial time series.
- Analyze of data series based on stochastic and non stochastic models

## Learning Outcomes {-}

- On successful completion of this course, students will be able to provide more than an introductory treatment of the topics.
- Students are encouraged to pursue further study in this area if they find that the topics covered in this course.

## Outline Syllabus {-}
 
- Definition and examples of time series
- back-shift and differencing-operators, - strong and weak stationarity, definition of ACF, PACF.
- Definitions and properties of the $MA(q), MA(\infty), AR(p), AR(\infty)$
and $ARMA(p,q)$,in particualr their acf's
- causal stationarity of AR
- invertibility of MA models and causal stationarity and invertibility of ARMA; - concept of spectral density function and its applications
- definition and properties of integrated $ARIMA(p,d,q)$ processes
- definition and properties of random walks with or without drift.
- Model selection following the AIC and BIC
- brief introduction to linear prediction and calculation of forecasting intervals for normal ARMA models
- point and interval forecasts for normal random walks with or without drift.
- Definition and properties of the VAR (vector autoregressive) model, arrange a univariate time series as a multivariate Markov model.
- Nonlinear properties of financial time series
- definition and properties of the well known ARCH, GARCH etc. 
- Cointegration in Single Equations, Modeling and Forecasting Financial Time Series.